[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.report]
fail_under = 100
exclude_lines = [
    'if TYPE_CHECKING:',
    'pragma: no cover'
]

[tool.poetry]
name = "REDCapRecordSynthesizer"
version = "1.1.0"
description = "Creates synthetic REDCap-like records for software testing."
authors = ["Kevin J. Delaney <kjdelaney@ucsd.edu>"]
readme = "README.md"

documentation = "https://github.com/DBMI/REDCapRecordSynthesizer"
homepage = "https://github.com/DBMI/REDCapRecordSynthesizer"
repository = "https://github.com/DBMI/REDCapRecordSynthesizer"

packages = [
    { include = "redcaprecordsynthesizer", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
faker = "^15.3.4"
pandas = ">=2.2.0"
pre-commit = "^2.21.0"
redcaputilities = {git = "https://github.com/DBMI/REDCapUtilities.git"}

[tool.poetry.group.dev.dependencies]
anybadge = "*"
make = "*"
mkdocs = "*"
mkdocstrings = "*"
mkdocs-material = "*"
pep8-naming = "*"
pre-commit = "*"
pymdown-extensions = "*"
pytest = "*"
pytest-github-actions-annotate-failures = "*"
pytest-cov = "*"
python-kacl = "*"
pyupgrade = "*"
ruff = "*"
sphinx = "*"
sphinx_markdown_builder = "*"
typing = "3.7.4.3"
usaddress = "*"
wheel = "*"

[tool.pytest.ini_options]
pythonpath = [".", "src", "src/redcaprecordsynthesizer"]
testpaths= ["redcaprecordsynthesizer"]

[tools.setuptools]
include-package-data = true

[tools.setuptools.package-data]
mypkg = [".csv"]

[tools.setuptools.packages.find]
where = ["src/redcaprecordsynthesizer/nickname_lookup/data"]
