import logging

import pandas  # type: ignore[import]

class FakeRecordGenerator:
    __log: logging.Logger = ...
    min_study_id: int = ...
    max_study_id: int = ...
    __range_study_id: range = ...
    __duplicate_study_id: bool = ...
    __existing_study_ids: list = ...

    def __init__(self) -> None: ...
    def __check_index_field_name(self, index_field_name: str) -> None: ...
    def __check_max_number_copies_of_one_record(
        self, max_number_copies_of_one_record: int
    ) -> None: ...
    def __check_num_records_desired(self, num_records_desired: int) -> None: ...
    def __check_percent_records_to_duplicate(
        self, percent_records_to_duplicate: float
    ) -> None: ...
    def __create_fake_email_address(self, given_name: str, surname: str) -> str: ...
    def __create_fake_record(self, next_study_id: int) -> dict: ...
    def create_fake_records(
        self,
        index_field_name: str = ...,
        max_number_copies_of_one_record: int = ...,
        num_records_desired: int = ...,
        percent_records_to_duplicate: float = ...,
    ) -> pandas.DataFrame: ...
    def create_fake_study_id(self) -> int: ...
    def __duplicate_record(
        self,
        record: pandas.DataFrame,
        medical_record_numbers: list,
        nicknames: list,
        state_name: str,
    ) -> pandas.DataFrame: ...
    def __initialize_fake_records(
        self, num_records_desired: int, study_ids: list
    ) -> pandas.DataFrame: ...
