class NicknameGenerator:
    __names: dict = None

    def __init__(self, filename: str | None = ...) -> None: ...
    def get(self, name: str, default: str | None = ...) -> None | str | list: ...
    @classmethod
    def __names_file(cls): ...
